import Head from 'next/head';
import {Outfit} from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Image from 'next/image';

const outfit = Outfit({subsets: ['latin'], variable: '--font-family-main'});

export default function Home() {
  return (
    <>
      <Head>
        <title>Qr Code Component</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${outfit.variable} ${styles.container}`}>
        <div className={styles.qrImage}>
          <Image alt='qr-image' src={'./QR Image.svg'} fill style={{objectFit: 'cover'}} priority />
        </div>
        <div className={styles.qrMain}>
          <h1>Improve your front-end skills by building projects</h1>
          <p>
            Scan the QR code to visit Frontend Mentor and take your coding skills to the next level
          </p>
        </div>
      </main>
    </>
  );
}
